### ISSUE TITLE
Layer toggles across ergodox can get stuck in the wrong state

### ISSUE THREAD

**Issue by r4v5** [kiibohd/controller#66] opened 2015-10-19 05:03 UTC
With the "stock" ergodox layout, pressing the two f1 keys at the same time (across both keyboards) and then releasing them in order will lock the keyboard in Layer 1 until the process is repeated.

Steps to reproduce:
* Press down left half's f1 key
* Press down right half's f1 key
* Release left half's f1 key
* Release right half's f1 key
* Observe the keyboard thinks it's back on L1 now.

I'd expect f1 to be cleared when both keys are up, and if you release the second key before the first, this does indeed happen. Also, when using a layout that has multiple f1 keys on the same half-keyboard, this issue does not seem to manifest for those two keys, so it seems that operating across the split is required.

**Comment by haata** [comment] 2015-10-19 05:48
Yep, definitely a bug.
I've reproduced it here. I think the issue is that the shift current XOR's the current state. But since it's XOR'd twice it's getting confused.

I should be able to fix it in the next few days, but if someone gets impatient, this is where the code is:
https://github.com/kiibohd/controller/blob/master/Macro/PartialMap/macro.c#L171

**Comment by dumle29** [comment] 2015-12-17 01:47
Just wanted to chime in. Happens on my MD1 as well, with this layout ![image of my layout](http://i.imgur.com/jbD4doK.png)

**Comment by ntietz** [comment] 2016-10-09 17:55
I've also run into this on my Infinity Ergodox. I am interested in contributing a fix. @haata can you point me in the right direction on this?

**Comment by haata** [comment] 2016-10-09 18:03
Basically, in this function (and the functions calling it) https://github.com/kiibohd/controller/blob/master/Macro/PartialMap/macro.c#L139

I believe what's happening is I'm using an XOR instead of just a set/unset. This means if you pressed two Shift keys at different times (now the layer is temporarily unset). But release them at the same time (I think this is what's happening), it will only unset once.

It should be possible to fix this by strengthening the logic a bit more. Instead of blindly setting every time the function is called.

**Comment by ntietz** [comment] 2016-10-10 00:22
I've submitted a PR that should resolve the issue, assuming the CI checks are successful. On my Infinity Ergodox, it fixes things.

**Comment by ntietz** [comment] 2016-10-14 12:15
@haata I believe this has been resolved, can we close the issue?

**Comment by haata** [comment] 2016-10-14 17:52
Sure, still need to update the configurator, @jbondeson will take care of that.

**Closed by haata** 2016-10-14 17:52 UTC

**Comment by jbondeson** [comment] 2016-10-14 18:48
@haata Configurator has been updated.
